### PR TITLE
Update README.md after creating a dev branch

### PR DESCRIPTION
**Pull request by achin797**

### CODE REVIEW

**Review by eishan05 — CHANGES_REQUESTED** [review]
I want to enforce reviews on dev as well, but that's just me. Reviewing a merge request from dev to master would be asking for a lot because those pull requests would be very big (and hence hard to review and request changes). Reviewing small code changes into dev is faster and more productive.

**Review by michaelenglo — APPROVED** [review]
Totally agree

**Comment by michaelenglo** [comment]
@eishan05 I agree with what you said about making a small PR and enforcing reviews, although I still like the flexibility of pushing code to make trivial or in some cases urgent changes - what if we want to check in something very trivial like changing docs, or variable naming, etc?

Maybe the middle ground would be to enforce a pull request to be reviewed before merging to dev, but the author himself can also approve the PR. The reason for this is because we trust each other that we WILL NOT ever approve our code unless for whatever emergency reasons. But having it enforced will prevent people from accidentally pushing/merging unresolved PRs.

**Review by eishan05 — APPROVED** [review]

**Comment by eishan05** [comment]
Makes sense. I'll add the flexibility of self approval.

**Pull request merged**
